# Generated by Django 3.2.7 on 2021-09-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_auth_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='authentication.user')),
                ('student_number', models.CharField(max_length=10, unique=True)),
                ('nusnet_id', models.CharField(max_length=10, unique=True)),
                ('telegram_handle', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='auth_provider',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nusnet_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_handle',
        ),
    ]
