# Generated by Django 3.2.7 on 2021-09-14 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20210914_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banner_url',
            field=models.CharField(blank=True, default='https://images.pexels.com/photos/61135/pexels-photo-61135.jpeg', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='groups.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.tag'),
        ),
    ]
