# Generated by Django 3.2.7 on 2021-09-18 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0008_alter_group_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='banner_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='groups'),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(through='groups.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
