# Generated by Django 3.2.7 on 2021-09-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_signup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'ordering': ['created_at']},
        ),
        migrations.AddConstraint(
            model_name='signup',
            constraint=models.UniqueConstraint(fields=('slot', 'user'), name='unique_signup'),
        ),
    ]
