# Generated by Django 3.2.7 on 2021-09-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210917_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='has_attended',
            field=models.BooleanField(default=False),
        ),
    ]
