# Generated by Django 3.2.7 on 2021-09-19 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_signup_has_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='events'),
        ),
    ]
